/*
 * 共有単語帳データ（アプリに組み込まれた単語帳）
 * ここに書かれた内容は、URLを開いた全員に共通で表示されます。
 * 単語帳を追加・更新したいときは、内容をClaudeに伝えてください。
 * このファイルを書き換えて公開することで、全PCに自動で反映されます。
 */
const sharedWordBooks = [
  {
    id: "sample-english",
    name: "サンプル英単語帳（デモ用）",
    entries: [
      { number: 1, word: "apple", meaning: "りんご" },
      { number: 2, word: "book", meaning: "本" },
      { number: 3, word: "cat", meaning: "猫" },
      { number: 4, word: "dog", meaning: "犬" },
      { number: 5, word: "egg", meaning: "卵" },
      { number: 6, word: "fish", meaning: "魚" },
      { number: 7, word: "green", meaning: "緑" },
      { number: 8, word: "house", meaning: "家" },
      { number: 9, word: "ink", meaning: "インク" },
      { number: 10, word: "jump", meaning: "跳ぶ" },
      { number: 11, word: "kind", meaning: "親切な" },
      { number: 12, word: "lion", meaning: "ライオン" },
      { number: 13, word: "moon", meaning: "月" },
      { number: 14, word: "night", meaning: "夜" },
      { number: 15, word: "open", meaning: "開ける" },
    ],
  },
  {
    id: "sample-kobun",
    name: "サンプル古語単語帳（デモ用）",
    entries: [
      { number: 1, word: "あいなし", meaning: "つまらない・気にくわない" },
      { number: 2, word: "いと", meaning: "とても" },
      { number: 3, word: "うつつ", meaning: "現実" },
      { number: 4, word: "おとなし", meaning: "大人びている" },
      { number: 5, word: "かなし", meaning: "いとしい" },
      { number: 6, word: "きこゆ", meaning: "申し上げる" },
      { number: 7, word: "こころざし", meaning: "気持ち・愛情" },
      { number: 8, word: "しるし", meaning: "効果・証拠" },
      { number: 9, word: "つとめて", meaning: "早朝" },
      { number: 10, word: "ののしる", meaning: "大声で騒ぐ" },
    ],
  },
  {
    id: "chugaku-eitango-700",
    name: "中学英単語700",
    entries: [
      { number: 1, word: "picture", meaning: "絵、写真" },
      { number: 2, word: "computer", meaning: "コンピューター" },
      { number: 3, word: "magazine", meaning: "雑誌" },
      { number: 4, word: "letter", meaning: "手紙、文字" },
      { number: 5, word: "table", meaning: "テーブル、食卓" },
      { number: 6, word: "kitchen", meaning: "台所" },
      { number: 7, word: "chopstick", meaning: "(食事用の)はし" },
      { number: 8, word: "bedroom", meaning: "寝室" },
      { number: 9, word: "brush", meaning: "ブラシ" },
      { number: 10, word: "video", meaning: "ビデオ" },
      { number: 11, word: "suitcase", meaning: "スーツケース" },
      { number: 12, word: "key", meaning: "かぎ" },
      { number: 13, word: "window", meaning: "窓" },
      { number: 14, word: "pet", meaning: "ペット" },
      { number: 15, word: "yesterday", meaning: "昨日" },
      { number: 16, word: "tomorrow", meaning: "明日" },
      { number: 17, word: "now", meaning: "今" },
      { number: 18, word: "hour", meaning: "1時間、時刻" },
      { number: 19, word: "minute", meaning: "分" },
      { number: 20, word: "month", meaning: "1カ月、月" },
      { number: 21, word: "year", meaning: "年、〜歳" },
      { number: 22, word: "lunchtime", meaning: "昼食時間、ランチタイム" },
      { number: 23, word: "homework", meaning: "宿題" },
      { number: 24, word: "test", meaning: "テスト、試験" },
      { number: 25, word: "class", meaning: "クラス、学級、授業" },
      { number: 26, word: "classmate", meaning: "クラスメート、同級生" },
      { number: 27, word: "lesson", meaning: "授業、(教科書などの)課" },
      { number: 28, word: "subject", meaning: "教科、科目、話題" },
      { number: 29, word: "math", meaning: "数学" },
      { number: 30, word: "science", meaning: "科学、理科" },
      { number: 31, word: "history", meaning: "歴史" },
      { number: 32, word: "speech", meaning: "話すこと、演説、スピーチ" },
      { number: 33, word: "report", meaning: "報告(書)、レポート" },
      { number: 34, word: "textbook", meaning: "教科書" },
      { number: 35, word: "notebook", meaning: "ノート" },
      { number: 36, word: "page", meaning: "(本の)ページ" },
      { number: 37, word: "cafeteria", meaning: "カフェテリア、(学校などの)食堂" },
      { number: 38, word: "library", meaning: "図書館" },
      { number: 39, word: "gym", meaning: "体育館" },
      { number: 40, word: "club", meaning: "クラブ、部" },
      { number: 41, word: "college", meaning: "大学、単科大学" },
      { number: 42, word: "university", meaning: "(総合)大学" },
      { number: 43, word: "course", meaning: "進路、科目" },
      { number: 44, word: "contest", meaning: "競技会、コンテスト" },
      { number: 45, word: "group", meaning: "集団、グループ" },
      { number: 46, word: "member", meaning: "一員、会員、部員" },
      { number: 47, word: "park", meaning: "公園、運動場" },
      { number: 48, word: "restaurant", meaning: "レストラン" },
      { number: 49, word: "store", meaning: "店" },
      { number: 50, word: "bookstore", meaning: "書店" },
      { number: 51, word: "museum", meaning: "博物館、美術館" },
      { number: 52, word: "station", meaning: "駅" },
      { number: 53, word: "train", meaning: "列車、電車" },
      { number: 54, word: "airport", meaning: "空港、飛行場" },
      { number: 55, word: "bike", meaning: "自転車" },
      { number: 56, word: "street", meaning: "通り" },
      { number: 57, word: "road", meaning: "道、道路" },
      { number: 58, word: "place", meaning: "場所" },
      { number: 59, word: "hospital", meaning: "病院" },
      { number: 60, word: "hotel", meaning: "ホテル" },
      { number: 61, word: "pool", meaning: "プール" },
      { number: 62, word: "apartment", meaning: "アパート" },
      { number: 63, word: "garden", meaning: "庭、庭園" },
      { number: 64, word: "zoo", meaning: "動物園" },
      { number: 65, word: "town", meaning: "町" },
      { number: 66, word: "building", meaning: "建物、ビル" },
      { number: 67, word: "company", meaning: "会社" },
      { number: 68, word: "office", meaning: "事務所、会社、役所" },
      { number: 69, word: "bank", meaning: "銀行" },
      { number: 70, word: "ship", meaning: "(大型の)船" },
      { number: 71, word: "party", meaning: "パーティー" },
      { number: 72, word: "game", meaning: "遊び、ゲーム、試合" },
      { number: 73, word: "shopping", meaning: "買い物" },
      { number: 74, word: "present", meaning: "贈り物、プレゼント" },
      { number: 75, word: "weekend", meaning: "週末" },
      { number: 76, word: "holiday", meaning: "祝日、休暇" },
      { number: 77, word: "movie", meaning: "映画" },
      { number: 78, word: "program", meaning: "番組、計画" },
      { number: 79, word: "trip", meaning: "(短期間の)旅行" },
      { number: 80, word: "camera", meaning: "カメラ" },
      { number: 81, word: "picnic", meaning: "ピクニック、遠足" },
      { number: 82, word: "fishing", meaning: "魚釣り" },
      { number: 83, word: "camp", meaning: "キャンプ、キャンプ場" },
      { number: 84, word: "hobby", meaning: "趣味" },
      { number: 85, word: "face", meaning: "顔" },
      { number: 86, word: "eye", meaning: "目" },
      { number: 87, word: "hair", meaning: "髪の毛、毛" },
      { number: 88, word: "arm", meaning: "腕" },
      { number: 89, word: "fever", meaning: "熱" },
      { number: 90, word: "job", meaning: "仕事、職" },
      { number: 91, word: "doctor", meaning: "医者" },
      { number: 92, word: "dentist", meaning: "歯科医" },
      { number: 93, word: "scientist", meaning: "科学者" },
      { number: 94, word: "pilot", meaning: "パイロット" },
      { number: 95, word: "actor", meaning: "俳優" },
      { number: 96, word: "volunteer", meaning: "ボランティア、進んでやる人" },
      { number: 97, word: "grandmother", meaning: "祖母、おばあさん" },
      { number: 98, word: "grandfather", meaning: "祖父、おじいさん" },
      { number: 99, word: "parent", meaning: "親" },
      { number: 100, word: "husband", meaning: "夫" },
      { number: 101, word: "son", meaning: "息子" },
      { number: 102, word: "aunt", meaning: "おば" },
      { number: 103, word: "food", meaning: "食べ物" },
      { number: 104, word: "pizza", meaning: "ピザ" },
      { number: 105, word: "cheese", meaning: "チーズ" },
      { number: 106, word: "soup", meaning: "スープ" },
      { number: 107, word: "salad", meaning: "サラダ" },
      { number: 108, word: "vegetable", meaning: "野菜" },
      { number: 109, word: "toast", meaning: "トースト" },
      { number: 110, word: "hamburger", meaning: "ハンバーガー" },
      { number: 111, word: "pancake", meaning: "パンケーキ" },
      { number: 112, word: "chocolate", meaning: "チョコレート" },
      { number: 113, word: "coffee", meaning: "コーヒー" },
      { number: 114, word: "juice", meaning: "ジュース" },
      { number: 115, word: "popcorn", meaning: "ポップコーン" },
      { number: 116, word: "menu", meaning: "メニュー" },
      { number: 117, word: "dish", meaning: "皿、料理" },
      { number: 118, word: "weather", meaning: "天気、天候" },
      { number: 119, word: "rain", meaning: "雨" },
      { number: 120, word: "water", meaning: "水" },
      { number: 121, word: "river", meaning: "川、河" },
      { number: 122, word: "beach", meaning: "浜、海辺" },
      { number: 123, word: "mountain", meaning: "山、(mountainsで)山脈" },
      { number: 124, word: "star", meaning: "星" },
      { number: 125, word: "flower", meaning: "花" },
      { number: 126, word: "rose", meaning: "バラ" },
      { number: 127, word: "animal", meaning: "動物" },
      { number: 128, word: "practice", meaning: "練習" },
      { number: 129, word: "guitar", meaning: "ギター" },
      { number: 130, word: "violin", meaning: "バイオリン" },
      { number: 131, word: "sound", meaning: "音" },
      { number: 132, word: "concert", meaning: "音楽会、コンサート" },
      { number: 133, word: "musical", meaning: "ミュージカル" },
      { number: 134, word: "shirt", meaning: "ワイシャツ、シャツ" },
      { number: 135, word: "dress", meaning: "ドレス、服装" },
      { number: 136, word: "color", meaning: "色" },
      { number: 137, word: "purple", meaning: "紫色" },
      { number: 138, word: "Japan", meaning: "日本" },
      { number: 139, word: "Spain", meaning: "スペイン" },
      { number: 140, word: "England", meaning: "イングランド" },
      { number: 141, word: "Africa", meaning: "アフリカ" },
      { number: 142, word: "India", meaning: "インド" },
      { number: 143, word: "soccer", meaning: "サッカー" },
      { number: 144, word: "basketball", meaning: "バスケットボール" },
      { number: 145, word: "volleyball", meaning: "バレーボール" },
      { number: 146, word: "badminton", meaning: "バドミントン" },
      { number: 147, word: "racket", meaning: "(テニスなどの)ラケット" },
      { number: 148, word: "jogging", meaning: "ジョギング" },
      { number: 149, word: "goal", meaning: "(サッカーなどの)ゴール、(ゴールに入れた)得点、目標" },
      { number: 150, word: "kind", meaning: "種類" },
      { number: 151, word: "e-mail", meaning: "電子メール、Eメール" },
      { number: 152, word: "information", meaning: "情報" },
      { number: 153, word: "thing", meaning: "物、こと" },
      { number: 154, word: "story", meaning: "物語、話" },
      { number: 155, word: "word", meaning: "語、単語、言葉" },
      { number: 156, word: "future", meaning: "未来、将来" },
      { number: 157, word: "cell phone", meaning: "携帯電話" },
      { number: 158, word: "event", meaning: "行事、できごと" },
      { number: 159, word: "culture", meaning: "文化" },
      { number: 160, word: "center", meaning: "中心、中央" },
      { number: 161, word: "meeting", meaning: "会、会議" },
      { number: 162, word: "ticket", meaning: "切符、チケット" },
      { number: 163, word: "sale", meaning: "販売、特売、バーゲンセール" },
      { number: 164, word: "money", meaning: "お金" },
      { number: 165, word: "line", meaning: "線、行列、(電車などの)路線" },
      { number: 166, word: "end", meaning: "終わり" },
      { number: 167, word: "front", meaning: "正面、前面" },
      { number: 168, word: "way", meaning: "道、方向、方法" },
      { number: 169, word: "race", meaning: "レース、競走" },
      { number: 170, word: "plan", meaning: "計画" },
      { number: 171, word: "fun", meaning: "楽しみ" },
      { number: 172, word: "example", meaning: "例" },
      { number: 173, word: "postcard", meaning: "はがき" },
      { number: 174, word: "poster", meaning: "ポスター" },
      { number: 175, word: "robot", meaning: "ロボット" },
      { number: 176, word: "like", meaning: "好きである" },
      { number: 177, word: "like", meaning: "が好きである、を好む" },
      { number: 178, word: "get", meaning: "(を)得る、に着く" },
      { number: 179, word: "visit", meaning: "(を)訪れる" },
      { number: 180, word: "visit", meaning: "(を)訪問する、(を)訪れる" },
      { number: 181, word: "come", meaning: "来る、(相手のほうへ)行く" },
      { number: 182, word: "see", meaning: "(が)見える、に会う" },
      { number: 183, word: "take", meaning: "(を)取る、(乗り物)に乗る、を持っていく、を連れていく" },
      { number: 184, word: "make", meaning: "(を)作る" },
      { number: 185, word: "look", meaning: "(注意して)見る" },
      { number: 186, word: "watch", meaning: "(を)じっと見る" },
      { number: 187, word: "meet", meaning: "(に)会う" },
      { number: 188, word: "talk", meaning: "(を)話す" },
      { number: 189, word: "say", meaning: "(と)言う、話す" },
      { number: 190, word: "tell", meaning: "(を)話す、言う" },
      { number: 191, word: "speak", meaning: "(を)話す、演説する" },
      { number: 192, word: "listen", meaning: "(注意して)聞く" },
      { number: 193, word: "hear", meaning: "が聞こえる" },
      { number: 194, word: "ask", meaning: "(を)たずねる、質問する、(を)頼む" },
      { number: 195, word: "answer", meaning: "(に)答える、(電話・訪問)(に)応じる" },
      { number: 196, word: "stay", meaning: "とどまる、泊まる、滞在する" },
      { number: 197, word: "live", meaning: "住む、暮らす" },
      { number: 198, word: "wake", meaning: "目が覚める、を起こす" },
      { number: 199, word: "work", meaning: "働く、勉強する" },
      { number: 200, word: "eat", meaning: "(を)食べる" },
      { number: 201, word: "drink", meaning: "(を)飲む" },
      { number: 202, word: "give", meaning: "を与える、をあげる" },
      { number: 203, word: "bring", meaning: "を持ってくる、を連れてくる" },
      { number: 204, word: "love", meaning: "を愛する、が大好きである" },
      { number: 205, word: "find", meaning: "を見つける" },
      { number: 206, word: "need", meaning: "を必要とする" },
      { number: 207, word: "feel", meaning: "(を)感じる、(と)思う" },
      { number: 208, word: "enjoy", meaning: "を楽しむ" },
      { number: 209, word: "finish", meaning: "(を)終える、終わる" },
      { number: 210, word: "lose", meaning: "をなくす、(に)負ける" },
      { number: 211, word: "write", meaning: "(を)書く、(に)手紙を書く" },
      { number: 212, word: "forget", meaning: "(を)忘れる" },
      { number: 213, word: "swim", meaning: "泳ぐ" },
      { number: 214, word: "read", meaning: "(を)読む" },
      { number: 215, word: "paint", meaning: "(絵の具で)かく、にペンキを塗る" },
      { number: 216, word: "cut", meaning: "を切る" },
      { number: 217, word: "run", meaning: "走る" },
      { number: 218, word: "call", meaning: "(を)呼ぶ、に電話する" },
      { number: 219, word: "drive", meaning: "(自動車などを)運転する" },
      { number: 220, word: "ride", meaning: "に乗る" },
      { number: 221, word: "join", meaning: "に加わる、参加する" },
      { number: 222, word: "invite", meaning: "を招待する" },
      { number: 223, word: "know", meaning: "(を)知っている" },
      { number: 224, word: "show", meaning: "を見せる" },
      { number: 225, word: "wash", meaning: "(を)洗う" },
      { number: 226, word: "teach", meaning: "を教える" },
      { number: 227, word: "think", meaning: "(と)思う、考える" },
      { number: 228, word: "hope", meaning: "を望む、(~だと)いいと思う" },
      { number: 229, word: "worry", meaning: "心配する、を心配させる" },
      { number: 230, word: "try", meaning: "をためす、(~しようと)努力する" },
      { number: 231, word: "hurry", meaning: "急ぐ、を急がせる" },
      { number: 232, word: "arrive", meaning: "着く、到着する" },
      { number: 233, word: "wear", meaning: "を着ている、を身につけている" },
      { number: 234, word: "change", meaning: "を変える、変わる" },
      { number: 235, word: "become", meaning: "になる" },
      { number: 236, word: "catch", meaning: "をつかまえる" },
      { number: 237, word: "put", meaning: "を置く" },
      { number: 238, word: "order", meaning: "を注文する" },
      { number: 239, word: "sell", meaning: "を売る" },
      { number: 240, word: "stop", meaning: "をやめる、止まる" },
      { number: 241, word: "sing", meaning: "(を)歌う" },
      { number: 242, word: "break", meaning: "をこわす、を折る、こわれる" },
      { number: 243, word: "fall", meaning: "落ちる、転ぶ" },
      { number: 244, word: "turn", meaning: "をまわす、まわる" },
      { number: 245, word: "last", meaning: "最後の、この前の" },
      { number: 246, word: "first", meaning: "第1の、最初の" },
      { number: 247, word: "good", meaning: "よい、おいしい、親切な、楽しい、じょうずな" },
      { number: 248, word: "bad", meaning: "悪い" },
      { number: 249, word: "late", meaning: "(時間・時期が)遅い、遅れた" },
      { number: 250, word: "early", meaning: "早い、初期の" },
      { number: 251, word: "fast", meaning: "速い" },
      { number: 252, word: "slow", meaning: "遅い、のろい" },
      { number: 253, word: "favorite", meaning: "大好きな、お気に入りの" },
      { number: 254, word: "happy", meaning: "幸福な、楽しい、うれしい" },
      { number: 255, word: "lucky", meaning: "運のよい、幸運な" },
      { number: 256, word: "free", meaning: "自由な、ひまな、無料の" },
      { number: 257, word: "next", meaning: "次の、今度の" },
      { number: 258, word: "all", meaning: "すべての" },
      { number: 259, word: "half", meaning: "半分の" },
      { number: 260, word: "fine", meaning: "すばらしい、晴れた、健康で" },
      { number: 261, word: "sick", meaning: "病気の、病気で" },
      { number: 262, word: "hungry", meaning: "空腹の、おなかがすいた" },
      { number: 263, word: "sorry", meaning: "すまないと思って、気の毒で" },
      { number: 264, word: "near", meaning: "(距離・時間が)近い" },
      { number: 265, word: "ready", meaning: "用意ができて" },
      { number: 266, word: "open", meaning: "開いた" },
      { number: 267, word: "famous", meaning: "有名な" },
      { number: 268, word: "warm", meaning: "暖かい" },
      { number: 269, word: "quiet", meaning: "静かな" },
      { number: 270, word: "dark", meaning: "暗い、(色が)濃い、黒っぽい" },
      { number: 271, word: "interesting", meaning: "おもしろい、興味深い" },
      { number: 272, word: "special", meaning: "特別の" },
      { number: 273, word: "useful", meaning: "役に立つ" },
      { number: 274, word: "careful", meaning: "注意深い" },
      { number: 275, word: "difficult", meaning: "難しい" },
      { number: 276, word: "popular", meaning: "人気のある、流行の" },
      { number: 277, word: "small", meaning: "小さい" },
      { number: 278, word: "short", meaning: "短い、背の低い" },
      { number: 279, word: "beautiful", meaning: "美しい、すばらしい" },
      { number: 280, word: "cute", meaning: "かわいい" },
      { number: 281, word: "sunny", meaning: "太陽の照っている" },
      { number: 282, word: "cloudy", meaning: "くもった" },
      { number: 283, word: "snowy", meaning: "雪の降る、雪の積もった" },
      { number: 284, word: "hard", meaning: "難しい、かたい、熱心な" },
      { number: 285, word: "expensive", meaning: "高価な" },
      { number: 286, word: "delicious", meaning: "非常においしい" },
      { number: 287, word: "own", meaning: "自分自身の" },
      { number: 288, word: "other", meaning: "他の、別の" },
      { number: 289, word: "different", meaning: "ちがった、異なる、いろいろな" },
      { number: 290, word: "dear", meaning: "いとしい、親愛なる" },
      { number: 291, word: "so", meaning: "とても、そのように" },
      { number: 292, word: "really", meaning: "本当に、(日常会話で)まさか" },
      { number: 293, word: "often", meaning: "たびたび、よく" },
      { number: 294, word: "back", meaning: "後ろへ、後ろに、もとの所へ" },
      { number: 295, word: "soon", meaning: "まもなく、すぐに" },
      { number: 296, word: "together", meaning: "いっしょに、ともに" },
      { number: 297, word: "usually", meaning: "いつもは、ふつう" },
      { number: 298, word: "tonight", meaning: "今夜(は)" },
      { number: 299, word: "once", meaning: "1度、1回、かつて" },
      { number: 300, word: "again", meaning: "ふたたび、また" },
      { number: 301, word: "just", meaning: "ちょうど、ほんの" },
      { number: 302, word: "only", meaning: "ただ~だけ" },
      { number: 303, word: "there", meaning: "そこに、そこで、そこへ" },
      { number: 304, word: "still", meaning: "今でも、まだ" },
      { number: 305, word: "when", meaning: "いつ" },
      { number: 306, word: "also", meaning: "~もまた" },
      { number: 307, word: "maybe", meaning: "たぶん、ひょっとすると" },
      { number: 308, word: "later", meaning: "もっと遅く、後で" },
      { number: 309, word: "easily", meaning: "簡単に、楽々と" },
      { number: 310, word: "away", meaning: "離れて、あちらへ、留守で" },
      { number: 311, word: "off", meaning: "離れて、去って、脱いで" },
      { number: 312, word: "out", meaning: "外へ、外に、不在で" },
      { number: 313, word: "at", meaning: "(場所・位置を示して)~で、~に" },
      { number: 314, word: "in", meaning: "(場所・位置を示して)~の中に[で]、~内" },
      { number: 315, word: "for", meaning: "~のために" },
      { number: 316, word: "on", meaning: "~の上に" },
      { number: 317, word: "of", meaning: "(所有・所属を表して)~の" },
      { number: 318, word: "about", meaning: "~について(の)" },
      { number: 319, word: "with", meaning: "~といっしょに" },
      { number: 320, word: "after", meaning: "~の後に" },
      { number: 321, word: "by", meaning: "~のそばに、~によって、~までに(は)" },
      { number: 322, word: "under", meaning: "~の下に[を]、~未満の" },
      { number: 323, word: "over", meaning: "~の上に、~を越えて" },
      { number: 324, word: "around", meaning: "~のまわりを[に]、~中を" },
      { number: 325, word: "beside", meaning: "~のそばに" },
      { number: 326, word: "between", meaning: "~の間に、~の間で、~の間の" },
      { number: 327, word: "into", meaning: "~の中へ[に]" },
      { number: 328, word: "until", meaning: "~まで(ずっと)" },
      { number: 329, word: "and", meaning: "と、そして" },
      { number: 330, word: "but", meaning: "しかし" },
      { number: 331, word: "because", meaning: "(なぜなら)~だから、~なので" },
      { number: 332, word: "if", meaning: "もし~ならば" },
      { number: 333, word: "or", meaning: "か~、あるいは~" },
      { number: 334, word: "will", meaning: "(未来への意志を表して)~するつもりだ、(未来を表して)~だろう" },
      { number: 335, word: "may", meaning: "(許可を表して)~してもよい、(推量を表して)~かもしれない" },
      { number: 336, word: "should", meaning: "~すべきである、~したほうがよい" },
      { number: 337, word: "could", meaning: "(canの過去形)~することができた" },
      { number: 338, word: "would", meaning: "(Would you~?で)~してくださいませんか" },
      { number: 339, word: "must", meaning: "~しなければならない、(否定形で)~してはいけない" },
      { number: 340, word: "one", meaning: "(前に出た数えられる名詞の代わりとして)~もの、1つ" },
      { number: 341, word: "another", meaning: "もう1つ、別のもの、別の人" },
      { number: 342, word: "something", meaning: "(肯定文で)何か、あるもの" },
      { number: 343, word: "anything", meaning: "(疑問文・ifの文で)何か、(否定文で)何も、(肯定文で)何でも" },
      { number: 344, word: "everyone", meaning: "だれでも、みんな" },
      { number: 345, word: "better", meaning: "よりよい、よくなって" },
      { number: 346, word: "best", meaning: "最もよい、最もよく" },
      { number: 347, word: "much", meaning: "たくさんの、たいへん" },
      { number: 348, word: "more", meaning: "もっと多い、もっと" },
      { number: 349, word: "than", meaning: "~よりも" },
      { number: 350, word: "shower", meaning: "シャワー" },
      { number: 351, word: "bath", meaning: "入浴" },
      { number: 352, word: "bathroom", meaning: "浴室、トイレ" },
      { number: 353, word: "towel", meaning: "タオル" },
      { number: 354, word: "phone", meaning: "電話" },
      { number: 355, word: "radio", meaning: "ラジオ" },
      { number: 356, word: "newspaper", meaning: "新聞" },
      { number: 357, word: "photo", meaning: "写真" },
      { number: 358, word: "comic", meaning: "漫画本、コミック" },
      { number: 359, word: "sofa", meaning: "ソファー" },
      { number: 360, word: "door", meaning: "戸、ドア" },
      { number: 361, word: "glass", meaning: "ガラス、コップ" },
      { number: 362, word: "knife", meaning: "ナイフ" },
      { number: 363, word: "wallet", meaning: "さいふ、札入れ" },
      { number: 364, word: "calendar", meaning: "カレンダー" },
      { number: 365, word: "ruler", meaning: "定規" },
      { number: 366, word: "toy", meaning: "おもちゃ" },
      { number: 367, word: "doghouse", meaning: "犬小屋" },
      { number: 368, word: "date", meaning: "日付, デート" },
      { number: 369, word: "noon", meaning: "正午, 昼の12時" },
      { number: 370, word: "dictionary", meaning: "辞書, 辞典" },
      { number: 371, word: "paper", meaning: "紙, 答案用紙" },
      { number: 372, word: "question", meaning: "質問, 問題" },
      { number: 373, word: "floor", meaning: "床, (建物の)一階" },
      { number: 374, word: "classroom", meaning: "教室" },
      { number: 375, word: "blackboard", meaning: "黒板" },
      { number: 376, word: "eraser", meaning: "消しゴム, 黒板消し" },
      { number: 377, word: "map", meaning: "地図" },
      { number: 378, word: "uniform", meaning: "制服, ユニフォーム" },
      { number: 379, word: "grade", meaning: "成績の点数, 学年" },
      { number: 380, word: "drama", meaning: "ドラマ, 演劇" },
      { number: 381, word: "social studies", meaning: "社会科" },
      { number: 382, word: "bicycle", meaning: "自転車" },
      { number: 383, word: "taxi", meaning: "タクシー" },
      { number: 384, word: "airplane", meaning: "飛行機" },
      { number: 385, word: "plane", meaning: "飛行機" },
      { number: 386, word: "boat", meaning: "ボート, (小型の)船" },
      { number: 387, word: "bridge", meaning: "橋" },
      { number: 388, word: "supermarket", meaning: "スーパーマーケット" },
      { number: 389, word: "café", meaning: "喫茶店, カフェ" },
      { number: 390, word: "post office", meaning: "郵便局" },
      { number: 391, word: "stadium", meaning: "スタジアム, 競技場, 野球場" },
      { number: 392, word: "theater", meaning: "劇場" },
      { number: 393, word: "hall", meaning: "ホール, ろう下" },
      { number: 394, word: "farm", meaning: "農場, 農園" },
      { number: 395, word: "corner", meaning: "角, 曲がり角, すみ" },
      { number: 396, word: "hometown", meaning: "生まれ故郷" },
      { number: 397, word: "vacation", meaning: "休み, 休暇" },
      { number: 398, word: "travel", meaning: "旅行, (を)旅行する" },
      { number: 399, word: "festival", meaning: "祭り, ~祭" },
      { number: 400, word: "homestay", meaning: "ホームステイ" },
      { number: 401, word: "tent", meaning: "テント" },
      { number: 402, word: "painting", meaning: "絵, 絵画, 絵をかくこと" },
      { number: 403, word: "comedy", meaning: "喜劇, コメディー" },
      { number: 404, word: "gift", meaning: "贈り物" },
      { number: 405, word: "stomachache", meaning: "胃痛, 腹痛" },
      { number: 406, word: "headache", meaning: "頭痛" },
      { number: 407, word: "people", meaning: "人々" },
      { number: 408, word: "writer", meaning: "筆者, 作家" },
      { number: 409, word: "artist", meaning: "芸術家, 画家" },
      { number: 410, word: "singer", meaning: "歌手" },
      { number: 411, word: "pianist", meaning: "ピアニスト" },
      { number: 412, word: "driver", meaning: "運転手, ドライバー" },
      { number: 413, word: "waiter", meaning: "ウエーター" },
      { number: 414, word: "farmer", meaning: "農場主, 農場経営者" },
      { number: 415, word: "coach", meaning: "コーチ, 指導者" },
      { number: 416, word: "sir", meaning: "(男性に対して)お客さま" },
      { number: 417, word: "visitor", meaning: "訪問客, 宿泊客" },
      { number: 418, word: "wife", meaning: "妻" },
      { number: 419, word: "uncle", meaning: "おじ" },
      { number: 420, word: "baby", meaning: "赤ちゃん" },
      { number: 421, word: "children", meaning: "子供たち" },
      { number: 422, word: "daughter", meaning: "娘" },
      { number: 423, word: "cousin", meaning: "いとこ" },
      { number: 424, word: "wedding", meaning: "結婚式, 結婚記念日" },
      { number: 425, word: "dessert", meaning: "デザート" },
      { number: 426, word: "ice cream", meaning: "アイスクリーム" },
      { number: 427, word: "candy", meaning: "キャンディ" },
      { number: 428, word: "doughnut", meaning: "ドーナツ" },
      { number: 429, word: "cookie", meaning: "クッキー" },
      { number: 430, word: "pie", meaning: "パイ" },
      { number: 431, word: "butter", meaning: "バター" },
      { number: 432, word: "bread", meaning: "パン" },
      { number: 433, word: "sandwich", meaning: "サンドイッチ" },
      { number: 434, word: "spaghetti", meaning: "スパゲッティ" },
      { number: 435, word: "pasta", meaning: "パスタ" },
      { number: 436, word: "noodle", meaning: "めん類, ヌードル" },
      { number: 437, word: "rice", meaning: "米, ごはん" },
      { number: 438, word: "salt", meaning: "塩" },
      { number: 439, word: "beef", meaning: "牛肉" },
      { number: 440, word: "chicken", meaning: "トリ肉, ニワトリ" },
      { number: 441, word: "meat", meaning: "(食用の)肉" },
      { number: 442, word: "steak", meaning: "ステーキ" },
      { number: 443, word: "sausage", meaning: "ソーセージ" },
      { number: 444, word: "fruit", meaning: "果物" },
      { number: 445, word: "cherry", meaning: "サクランボ" },
      { number: 446, word: "strawberry", meaning: "イチゴ" },
      { number: 447, word: "pineapple", meaning: "パイナップル" },
      { number: 448, word: "pumpkin", meaning: "カボチャ" },
      { number: 449, word: "onion", meaning: "タマネギ" },
      { number: 450, word: "snack", meaning: "スナック, 軽食, おやつ" },
      { number: 451, word: "snow", meaning: "雪, 雪が降る" },
      { number: 452, word: "cloud", meaning: "雲" },
      { number: 453, word: "sun", meaning: "太陽, 日光" },
      { number: 454, word: "sky", meaning: "空" },
      { number: 455, word: "season", meaning: "季節" },
      { number: 456, word: "autumn", meaning: "秋" },
      { number: 457, word: "sea", meaning: "海" },
      { number: 458, word: "ocean", meaning: "(the oceanで)大洋, 海" },
      { number: 459, word: "turtle", meaning: "海ガメ" },
      { number: 460, word: "lake", meaning: "湖" },
      { number: 461, word: "horse", meaning: "馬" },
      { number: 462, word: "pig", meaning: "ブタ" },
      { number: 463, word: "hamster", meaning: "ハムスター" },
      { number: 464, word: "music", meaning: "音楽" },
      { number: 465, word: "musician", meaning: "音楽家, ミュージシャン" },
      { number: 466, word: "pop music", meaning: "ポピュラー音楽, ポップス" },
      { number: 467, word: "band", meaning: "楽団, バンド" },
      { number: 468, word: "drum", meaning: "ドラム" },
      { number: 469, word: "flute", meaning: "フルート" },
      { number: 470, word: "trumpet", meaning: "トランペット" },
      { number: 471, word: "clothes", meaning: "衣服" },
      { number: 472, word: "coat", meaning: "コート, 上着" },
      { number: 473, word: "sweater", meaning: "セーター" },
      { number: 474, word: "glove", meaning: "(ふつうglovesで)手袋, グローブ" },
      { number: 475, word: "tie", meaning: "ネクタイ" },
      { number: 476, word: "glasses", meaning: "メガネ" },
      { number: 477, word: "sock", meaning: "(ふつうsocksで)くつ下, ソックス" },
      { number: 478, word: "umbrella", meaning: "かさ" },
      { number: 479, word: "gray", meaning: "灰色, グレー" },
      { number: 480, word: "gold", meaning: "金" },
      { number: 481, word: "dollar", meaning: "(米国・カナダなどの貨幣単位)ドル" },
      { number: 482, word: "yen", meaning: "円" },
      { number: 483, word: "world", meaning: "世界, 世の中" },
      { number: 484, word: "country", meaning: "国, (theをつけて)いなか" },
      { number: 485, word: "America", meaning: "アメリカ(合衆国)" },
      { number: 486, word: "Canada", meaning: "カナダ" },
      { number: 487, word: "Australia", meaning: "オーストラリア" },
      { number: 488, word: "France", meaning: "フランス" },
      { number: 489, word: "Italy", meaning: "イタリア" },
      { number: 490, word: "China", meaning: "中国" },
      { number: 491, word: "Korea", meaning: "韓国[朝鮮]" },
      { number: 492, word: "Mexico", meaning: "メキシコ" },
      { number: 493, word: "London", meaning: "ロンドン" },
      { number: 494, word: "Hawaii", meaning: "(アメリカの)ハワイ州, ハワイ島" },
      { number: 495, word: "golf", meaning: "ゴルフ" },
      { number: 496, word: "football", meaning: "フットボール" },
      { number: 497, word: "bowling", meaning: "ボウリング" },
      { number: 498, word: "match", meaning: "試合, 競争相手" },
      { number: 499, word: "ice-skating", meaning: "アイススケート" },
      { number: 500, word: "surfing", meaning: "サーフィン, 波乗り" },
      { number: 501, word: "wrestling", meaning: "レスリング" },
      { number: 502, word: "idea", meaning: "考え, アイデア" },
      { number: 503, word: "news", meaning: "ニュース, 報道" },
      { number: 504, word: "problem", meaning: "問題" },
      { number: 505, word: "Internet", meaning: "(the Internetで)インターネット" },
      { number: 506, word: "website", meaning: "ウェブサイト" },
      { number: 507, word: "mail", meaning: "郵便(物)" },
      { number: 508, word: "message", meaning: "伝言, メッセージ" },
      { number: 509, word: "language", meaning: "言語, 言葉" },
      { number: 510, word: "card", meaning: "カード, はがき, トランプの札" },
      { number: 511, word: "stamp", meaning: "切手, 印" },
      { number: 512, word: "passport", meaning: "パスポート" },
      { number: 513, word: "Christmas", meaning: "クリスマス" },
      { number: 514, word: "dream", meaning: "夢" },
      { number: 515, word: "life", meaning: "生活, 生命, 一生, 人生" },
      { number: 516, word: "list", meaning: "リスト, 名簿" },
      { number: 517, word: "prize", meaning: "賞, 賞品, 賞金" },
      { number: 518, word: "haircut", meaning: "髪のカット, 散髪" },
      { number: 519, word: "size", meaning: "大きさ, 寸法" },
      { number: 520, word: "part", meaning: "部分, 役割" },
      { number: 521, word: "seat", meaning: "座席" },
      { number: 522, word: "machine", meaning: "機械" },
      { number: 523, word: "cook", meaning: "(を)料理する" },
      { number: 524, word: "leave", meaning: "(を)出発する, (を)去る, (を)置き忘れる" },
      { number: 525, word: "clean", meaning: "(を)きれいにする, そうじする" },
      { number: 526, word: "sleep", meaning: "眠る" },
      { number: 527, word: "begin", meaning: "(を)始める, 始まる" },
      { number: 528, word: "send", meaning: "(を)送る" },
      { number: 529, word: "learn", meaning: "(を)学ぶ, (を)習う" },
      { number: 530, word: "dance", meaning: "踊る" },
      { number: 531, word: "move", meaning: "を動かす, 動く, 引っ越す" },
      { number: 532, word: "sit", meaning: "すわる, すわっている" },
      { number: 533, word: "win", meaning: "(に)勝つ, を勝ち取る" },
      { number: 534, word: "carry", meaning: "を運ぶ, を持ち歩く" },
      { number: 535, word: "draw", meaning: "(線を)引く, (絵・図を)かく" },
      { number: 536, word: "surprise", meaning: "を驚かせる, をびっくりさせる" },
      { number: 537, word: "happen", meaning: "(偶然)起こる" },
      { number: 538, word: "smile", meaning: "ほほえむ" },
      { number: 539, word: "relax", meaning: "をくつろがせる, くつろぐ" },
      { number: 540, word: "check", meaning: "をチェックする, を点検する" },
      { number: 541, word: "remember", meaning: "(を)思い出す, (を)覚えている" },
      { number: 542, word: "understand", meaning: "(を)理解する" },
      { number: 543, word: "enter", meaning: "に入る" },
      { number: 544, word: "share", meaning: "を共有する, 分け合う" },
      { number: 545, word: "miss", meaning: "をのがす, がいなくてさびしく思う" },
      { number: 546, word: "rainy", meaning: "雨の, 雨降りの" },
      { number: 547, word: "windy", meaning: "風の吹く, 風の強い" },
      { number: 548, word: "cool", meaning: "涼しい, 冷たい, かっこいい" },
      { number: 549, word: "easy", meaning: "やさしい, 簡単な, 気楽な" },
      { number: 550, word: "heavy", meaning: "重い, 大量の" },
      { number: 551, word: "light", meaning: "軽い, 明るい" },
      { number: 552, word: "large", meaning: "大きい, 多数の, 多量の" },
      { number: 553, word: "medium", meaning: "中くらいの" },
      { number: 554, word: "little", meaning: "小さい, (小さくて)かわいらしい" },
      { number: 555, word: "busy", meaning: "忙しい, にぎやかな" },
      { number: 556, word: "tired", meaning: "疲れた, あきた" },
      { number: 557, word: "sleepy", meaning: "眠い, 眠そうな" },
      { number: 558, word: "healthy", meaning: "健康な" },
      { number: 559, word: "strong", meaning: "強い" },
      { number: 560, word: "angry", meaning: "怒った, 腹を立てた" },
      { number: 561, word: "sad", meaning: "悲しい" },
      { number: 562, word: "excited", meaning: "(人が)興奮した, わくわくした" },
      { number: 563, word: "exciting", meaning: "(人を)興奮させる, わくわくさせる" },
      { number: 564, word: "boring", meaning: "たいくつな, うんざりさせる" },
      { number: 565, word: "funny", meaning: "おかしな, おもしろい" },
      { number: 566, word: "sweet", meaning: "甘い" },
      { number: 567, word: "close", meaning: "ごく近い, 親密な" },
      { number: 568, word: "far", meaning: "遠い, 遠くに" },
      { number: 569, word: "wonderful", meaning: "すばらしい, すてきな" },
      { number: 570, word: "same", meaning: "同じ" },
      { number: 571, word: "both", meaning: "両方の, 両方" },
      { number: 572, word: "each", meaning: "それぞれの, 各自の, それぞれ, 各自" },
      { number: 573, word: "full", meaning: "いっぱいの, 満腹の" },
      { number: 574, word: "thirsty", meaning: "のどがかわいた" },
      { number: 575, word: "pretty", meaning: "きれいな, かわいらしい" },
      { number: 576, word: "dirty", meaning: "汚い, 汚れた" },
      { number: 577, word: "low", meaning: "低い, 低く" },
      { number: 578, word: "junior", meaning: "年下の, 年下の人" },
      { number: 579, word: "right", meaning: "正しい, 正確な, 右" },
      { number: 580, word: "wrong", meaning: "悪い, 間違った, 調子が悪い" },
      { number: 581, word: "quick", meaning: "(速度・動きが)速い，すばやい" },
      { number: 582, word: "professional", meaning: "専門の, プロの" },
      { number: 583, word: "well", meaning: "じょうずに, 十分に, 健康で" },
      { number: 584, word: "sometimes", meaning: "ときどき, ときには" },
      { number: 585, word: "twice", meaning: "2度, 2回" },
      { number: 586, word: "always", meaning: "いつも, 常に" },
      { number: 587, word: "o'clock", meaning: "~時" },
      { number: 588, word: "someday", meaning: "(未来の)いつか, そのうちに" },
      { number: 589, word: "already", meaning: "すでに, もう" },
      { number: 590, word: "slowly", meaning: "遅く，ゆっくりと" },
      { number: 591, word: "ago", meaning: "(今から)~前に" },
      { number: 592, word: "outside", meaning: "外に，外側に" },
      { number: 593, word: "before", meaning: "~の前に" },
      { number: 594, word: "during", meaning: "~の間ずっと，~の間のあるときに" },
      { number: 595, word: "shall", meaning: "(Shall I~?で)~しましょうか" },
      { number: 596, word: "mine", meaning: "私のもの" },
      { number: 597, word: "everything", meaning: "何もかも，みんな" },
      { number: 598, word: "most", meaning: "(many" },
      { number: 599, word: "a.m.", meaning: "午前" },
      { number: 600, word: "p.m.", meaning: "午後" },
      { number: 601, word: "want to do", meaning: "~したいと思う" },
      { number: 602, word: "like doing [to do]", meaning: "~するのが好きだ，~したい" },
      { number: 603, word: "want to be ~", meaning: "~になりたいと思う" },
      { number: 604, word: "need to do", meaning: "~する必要がある" },
      { number: 605, word: "go (back) home", meaning: "帰宅する" },
      { number: 606, word: "get home", meaning: "帰宅する" },
      { number: 607, word: "come home", meaning: "帰宅する" },
      { number: 608, word: "do one's homework", meaning: "宿題をする" },
      { number: 609, word: "take A to B", meaning: "AをBに連れていく" },
      { number: 610, word: "look for ~", meaning: "~を探す" },
      { number: 611, word: "leave (A) for B", meaning: "Bに向かって(Aを)出発する[離れる，去る]" },
      { number: 612, word: "have a good time", meaning: "楽しい時を過ごす" },
      { number: 613, word: "wait for ~", meaning: "~を待つ" },
      { number: 614, word: "stay in [at] ~", meaning: "(場所)に泊まる，(場所)に滞在する" },
      { number: 615, word: "stay with ~", meaning: "(人)の所に泊まる，(人)の所に滞在する" },
      { number: 616, word: "get up", meaning: "起きる，立ち上がる" },
      { number: 617, word: "wake up", meaning: "目が覚める" },
      { number: 618, word: "take a trip", meaning: "旅行をする" },
      { number: 619, word: "go on a trip", meaning: "旅行に行く" },
      { number: 620, word: "speak to ~", meaning: "~に話しかける，~と話す" },
      { number: 621, word: "talk to ~", meaning: "~に話をする" },
      { number: 622, word: "talk with ~", meaning: "~と話をする" },
      { number: 623, word: "listen to ~", meaning: "~を聞く，~に耳を傾ける" },
      { number: 624, word: "hear about ~", meaning: "~について聞く" },
      { number: 625, word: "go doing", meaning: "~しに行く" },
      { number: 626, word: "finish doing", meaning: "~し終える" },
      { number: 627, word: "enjoy doing", meaning: "~するのを楽しむ，楽しんで~する" },
      { number: 628, word: "go back to ~", meaning: "~へ戻る，~へ帰る" },
      { number: 629, word: "come back to ~", meaning: "~へ帰ってくる" },
      { number: 630, word: "get back", meaning: "戻る，帰る" },
      { number: 631, word: "come back from ~", meaning: "~から帰ってくる，~から戻ってくる" },
      { number: 632, word: "arrive at ~", meaning: "~に着く" },
      { number: 633, word: "arrive in ~", meaning: "~に着く" },
      { number: 634, word: "get to ~", meaning: "~に着く，~に到着する" },
      { number: 635, word: "start doing [to do]", meaning: "~し始める" },
      { number: 636, word: "stop doing", meaning: "~することをやめる" },
      { number: 637, word: "take a picture", meaning: "写真をとる" },
      { number: 638, word: "walk to ~", meaning: "~まで歩いて行く" },
      { number: 639, word: "ask ~ for help", meaning: "~に助けを求める" },
      { number: 640, word: "help A with B", meaning: "AのBを手伝う，AをB(のこと)で助ける" },
      { number: 641, word: "ask for ~", meaning: "~を求める" },
      { number: 642, word: "have a cold", meaning: "風邪をひいている" },
      { number: 643, word: "take a bath", meaning: "入浴する" },
      { number: 644, word: "take a shower", meaning: "シャワーを浴びる" },
      { number: 645, word: "take a walk", meaning: "散歩をする" },
      { number: 646, word: "go out", meaning: "外出する" },
      { number: 647, word: "say goodbye to ~", meaning: "~に別れのあいさつを言う" },
      { number: 648, word: "stay (at) home", meaning: "家にいる" },
      { number: 649, word: "think of ~", meaning: "~のことを考える，~を思い出す" },
      { number: 650, word: "become friends with ~", meaning: "~と友だちになる" },
      { number: 651, word: "catch a cold", meaning: "風邪をひく" },
      { number: 652, word: "get off ~", meaning: "~から降りる" },
      { number: 653, word: "give up", meaning: "あきらめる，やめる" },
      { number: 654, word: "have no idea", meaning: "まったくわからない" },
      { number: 655, word: "go around [round] ~", meaning: "~のまわりを回る" },
      { number: 656, word: "look around", meaning: "あたりを見回す" },
      { number: 657, word: "move to A (from B)", meaning: "(BからA)に引っ越す" },
      { number: 658, word: "write to ~", meaning: "~に手紙を書く" },
      { number: 659, word: "write back", meaning: "返事を書く" },
      { number: 660, word: "slow down", meaning: "速度を落とす，遅くする" },
      { number: 661, word: "worry about ~", meaning: "~のことを心配する" },
      { number: 662, word: "look like ~", meaning: "~に似ている，~のように見える" },
      { number: 663, word: "believe in ~", meaning: "~の存在を信じる，~を信用する" },
      { number: 664, word: "play catch", meaning: "キャッチボールをする" },
      { number: 665, word: "feel better", meaning: "気分がよくなる" },
      { number: 666, word: "a lot of ~", meaning: "たくさんの~" },
      { number: 667, word: "be late for ~", meaning: "~に遅れる，遅刻する" },
      { number: 668, word: "be careful", meaning: "気をつける" },
      { number: 669, word: "be interested in ~", meaning: "~に興味を持っている" },
      { number: 670, word: "kind of ~", meaning: "種類の~" },
      { number: 671, word: "a glass of ~", meaning: "コップ1杯の~" },
      { number: 672, word: "a cup of ~", meaning: "カップ1杯の~" },
      { number: 673, word: "in the morning", meaning: "午前中に，朝に" },
      { number: 674, word: "in the afternoon", meaning: "午後に" },
      { number: 675, word: "in the future", meaning: "将来" },
      { number: 676, word: "how long", meaning: "どれくらいの長さ" },
      { number: 677, word: "all day (long)", meaning: "1日中" },
      { number: 678, word: "for a long time", meaning: "長い間" },
      { number: 679, word: "last week", meaning: "先週" },
      { number: 680, word: "after work", meaning: "仕事の後で" },
      { number: 681, word: "for example", meaning: "たとえば" },
      { number: 682, word: "as ~ as ...", meaning: "…と同じくらい~" },
      { number: 683, word: "a lot", meaning: "たくさん，すいぶん" },
      { number: 684, word: "from A to B", meaning: "AからBまで，AからBへ" },
      { number: 685, word: "~ years old", meaning: "~歳" },
      { number: 686, word: "in front of ~", meaning: "~の前に[で]" },
      { number: 687, word: "next to ~", meaning: "~のとなりに" },
      { number: 688, word: "out of ~", meaning: "~から外へ" },
      { number: 689, word: "both A and B", meaning: "AとBの両方とも" },
      { number: 690, word: "one day", meaning: "(過去の)ある日，(未来の)いつか" },
      { number: 691, word: "(on) the first day", meaning: "第1日目に，初日に" },
      { number: 692, word: "on vacation", meaning: "休暇で" },
      { number: 693, word: "on foot", meaning: "歩いて，徒歩で" },
      { number: 694, word: "(just) around the corner", meaning: "角を曲がった所に" },
      { number: 695, word: "by the way", meaning: "ところで" },
      { number: 696, word: "more and more", meaning: "ますます多くの" },
      { number: 697, word: "for free", meaning: "無料で，ただで" },
      { number: 698, word: "right now", meaning: "今すぐに，現在，たった今" },
      { number: 699, word: "all over the world", meaning: "世界中で" },
      { number: 700, word: "have to do", meaning: "~しなければならない" },
    ],
  },
];
